### ISSUE TITLE
Git tags for releases?

### ISSUE THREAD

**Issue by samuela** [khdlr/augmax#5]
Would it be possible to get git tags for releases? I can see that the latest version is 0.2.2 according to pypi, but in order to build from source I'm not sure which commit that corresponds to. Having releases tagged helps when packaging augmax for other package managers, eg. nixpkgs.

**Comment by samuela** [comment]
for context, I'm working on getting augmax packaged here: https://github.com/NixOS/nixpkgs/pull/160946

**Comment by khdlr** [comment]
Hi Samuel, very cool! I fully support you in packaging the library.

The git tags exist, they just weren't pushed -- I forgot that you need to push git tags separately :sweat_smile: Will push them tonight when I'm on my dev machine.

Cheers,
Konrad

**Comment by khdlr** [comment]
The tags are now live @ https://github.com/khdlr/augmax/tags :)

**Comment by samuela** [comment]
Awesome, thank you so much, @khdlr! augmax is now packaged in nixpkgs: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/augmax/default.nix. I'll update to use the git tags on the next release/whenever I go to update the derivation again!
