### ISSUE TITLE
Example Syntax Error

### ISSUE THREAD

**Issue by guozhaosengzs** [khdlr/augmax#7]
Small issue, front page of GitHub, on
**Augmenting an entire batch of images on the GPU** page,
```
sub_rngs = jax.random.split(rng, images.shape[0])
transformed_images = jax.jit(jax.vmap(transform))(sub_rng, images)
```
The last _sub_rng_ should be changed to _sub_rngs_ .
Thanks!

**Comment by khdlr** [comment]
Nice catch, thanks for reporting this! :) Fixed with 48e9a991faf5c8f7c30f0740604b3f92691d72e5
