### ISSUE TITLE
Missing Github release for version 0.3.2

### ISSUE THREAD

**Issue by GaetanLepage** [khdlr/augmax#8]
Hello,

Would it be possible to create a git tag/release on Github for the latest Pypi version (0.3.2) ?

Thanks in advance !

**Comment by khdlr** [comment]
Sorry for the oversight, pushed the missing tags (v0.3.1 and v0.3.2) just now and added the corresponding releases.

**Comment by GaetanLepage** [comment]
Thank you very much !
