### ISSUE TITLE
Importing augmax runs JAX operations, preventing configuration

### ISSUE THREAD

**Issue by kvablack** [khdlr/augmax#9]
I believe importing augmax is running JAX operations, which "locks" some configuration fields that have to be set before JAX initializes. For example:

```python
import os
import jax

os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"

jax.random.key(0)  # does not preallocate the GPU
```

But with augmax:
```python
import os
import jax
import augmax # 75% of the GPU gets preallocated on this line

os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false" # has no effect
```

I took a quick look through the codebase, and I found [this line](https://github.com/khdlr/augmax/blob/27fdbd5b8901229319e0c624261c5b7a4ab5844d/augmax/geometric.py#L29) which could be it. Should be fixable by simply changing to `np.eye(3)`. There might be others that I missed, however.

You can import augmax lazily as a workaround, but that's giving me some nasty tracer leakage errors that are hard to debug (I think `self._current_transform` is becoming a tracer somehow?).

Great library otherwise, btw! Big fan.

**Comment by khdlr** [comment]
Good catch, and thanks for promptly providing a fix! :)

**Comment by khdlr** [comment]
Pushed v0.3.3 to PyPI just now, incorporating this fix. Thanks again! :blush:
